// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tScore
double tScore(arma::vec x1, arma::vec x2);
RcppExport SEXP tFDAprofile_tScore(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(tScore(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// projT
double projT(arma::mat X, arma::vec cl);
RcppExport SEXP tFDAprofile_projT(SEXP XSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(projT(X, cl));
    return rcpp_result_gen;
END_RCPP
}
// maxT
double maxT(arma::mat X, arma::vec cl);
RcppExport SEXP tFDAprofile_maxT(SEXP XSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(maxT(X, cl));
    return rcpp_result_gen;
END_RCPP
}
// tFDA
double tFDA(arma::mat X, arma::vec cl);
RcppExport SEXP tFDAprofile_tFDA(SEXP XSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(tFDA(X, cl));
    return rcpp_result_gen;
END_RCPP
}
// rotate
arma::mat rotate(arma::mat X, arma::vec cl);
RcppExport SEXP tFDAprofile_rotate(SEXP XSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(rotate(X, cl));
    return rcpp_result_gen;
END_RCPP
}
// tFDAprofile
List tFDAprofile(arma::mat X, arma::vec cl, double maxt_max, double projt_min, bool display_progress);
RcppExport SEXP tFDAprofile_tFDAprofile(SEXP XSEXP, SEXP clSEXP, SEXP maxt_maxSEXP, SEXP projt_minSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    Rcpp::traits::input_parameter< double >::type maxt_max(maxt_maxSEXP);
    Rcpp::traits::input_parameter< double >::type projt_min(projt_minSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(tFDAprofile(X, cl, maxt_max, projt_min, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// tFDAquadrant
List tFDAquadrant(arma::mat X, arma::vec cl, double maxt_max, double projt_min, int top, bool display_progress);
RcppExport SEXP tFDAprofile_tFDAquadrant(SEXP XSEXP, SEXP clSEXP, SEXP maxt_maxSEXP, SEXP projt_minSEXP, SEXP topSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    Rcpp::traits::input_parameter< double >::type maxt_max(maxt_maxSEXP);
    Rcpp::traits::input_parameter< double >::type projt_min(projt_minSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(tFDAquadrant(X, cl, maxt_max, projt_min, top, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// tFDAqprop
List tFDAqprop(arma::mat X, arma::vec cl, double maxt_max, double projt_min, bool display_progress);
RcppExport SEXP tFDAprofile_tFDAqprop(SEXP XSEXP, SEXP clSEXP, SEXP maxt_maxSEXP, SEXP projt_minSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl(clSEXP);
    Rcpp::traits::input_parameter< double >::type maxt_max(maxt_maxSEXP);
    Rcpp::traits::input_parameter< double >::type projt_min(projt_minSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(tFDAqprop(X, cl, maxt_max, projt_min, display_progress));
    return rcpp_result_gen;
END_RCPP
}
