# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tScore <- function(x1, x2) {
    .Call('tFDAprofile_tScore', PACKAGE = 'tFDAprofile', x1, x2)
}

projT <- function(X, cl) {
    .Call('tFDAprofile_projT', PACKAGE = 'tFDAprofile', X, cl)
}

maxT <- function(X, cl) {
    .Call('tFDAprofile_maxT', PACKAGE = 'tFDAprofile', X, cl)
}

tFDA <- function(X, cl) {
    .Call('tFDAprofile_tFDA', PACKAGE = 'tFDAprofile', X, cl)
}

rotate <- function(X, cl) {
    .Call('tFDAprofile_rotate', PACKAGE = 'tFDAprofile', X, cl)
}

tFDAprofile <- function(X, cl, maxt_max = 1.96, projt_min = 1.96, display_progress = TRUE) {
    .Call('tFDAprofile_tFDAprofile', PACKAGE = 'tFDAprofile', X, cl, maxt_max, projt_min, display_progress)
}

tFDAquadrant <- function(X, cl, maxt_max = 1.96, projt_min = 1.96, top = 100L, display_progress = TRUE) {
    .Call('tFDAprofile_tFDAquadrant', PACKAGE = 'tFDAprofile', X, cl, maxt_max, projt_min, top, display_progress)
}

tFDAqprop <- function(X, cl, maxt_max = 1.96, projt_min = 1.96, display_progress = TRUE) {
    .Call('tFDAprofile_tFDAqprop', PACKAGE = 'tFDAprofile', X, cl, maxt_max, projt_min, display_progress)
}

